config/routes.rb
Rails.application.routes.draw do
  root 'root#welcome'

  get '/auth/github', as: :login
  get '/auth/github/callback', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy'

  get '/search', to: 'explore#search'

  get 'users/:user_id/repos/:id/specific_repo_data', to: 'repos#specific_repo_data', defaults: {format: :json}
  get 'users/:user_id/repos/:id/language_data', to: 'repos#language_data', defaults: {format: :json}
  get 'users/:user_id/repos/:id/commit_data', to: 'repos#commit_data', defaults: {format: :json}
  get 'users/:user_id/repos/:id/commit_activity', to: 'repos#commit_activity', defaults: {format: :json}
  get 'users/:user_id/repos/:id/contributor_data', to: 'repos#contributor_data', defaults: {format: :json}
  get 'users/:user_id/repos/:id/code_frequency', to: 'repos#code_frequency', defaults: {format: :json}
  get 'users/:user_id/repos/:id/pull_requests', to: 'repos#pull_requests', defaults: {format: :json}

  get 'users/:id/repo_data', to: 'users#repo_data', defaults: {format: :json}
  get 'users/:id/follower_data', to: 'users#follower_data', defaults: {format: :json}
  get 'users/:id/user_data', to: 'users#user_data', defaults: {format: :json}

  get '/explore', to: 'explore#index'

  resources :users, only: [:show] do
    resources :repos, only: [:index, :show]
  end
end

app/models/repo.rb
class Repo
  def self.service
    GithubService.new
  end

  def self.specific_repo_data(user_name, repo_name)
    service.specific_repo_data(user_name, repo_name)
  end

  def self.commit_data(user_name, repo_name)
    service.commit_data(user_name, repo_name)
  end

  def self.commit_activity(user_name, repo_name)
    service.commit_data(user_name, repo_name).map do |commit|
      {week: parse_time(commit.week), amount: commit.total}
    end
  end

  def self.language_data(user_name, repo_name)
    service.language_data(user_name, repo_name).map do |name, size|
      {"label" => name, "value" => size}
    end
  end

  def self.contributor_data(user_name, repo_name)
    service.contributor_data(user_name, repo_name).map do |contribution|
      {label: contribution.author.login, value: contribution.total}
    end
  end

  def self.code_frequency(user_name, repo_name)
    service.code_frequency(user_name, repo_name).map do |week|
      {name: week[0], value: week[1], value2: week[2]}
    end
  end

  def self.pull_requests(user_name, repo_name)
    stuff = service.pull_requests(user_name, repo_name).map(&:state).inject(Hash.new(0)) {|hash,word| hash[word] += 1; hash}
    stuff.map do |state, count|
      {"label" => state, "value" => count}
    end
  end

  def self.parse_time(time)
    DateTime.strptime(time.to_s, '%s').strftime("%e-%b-%y")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.nickname           = auth_info.extra.raw_info.login
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end

  def self.service
    GithubService.new
  end

  def self.search(user)
    service.search(user)
  end

  def self.repo_data(user)
    service.repo_data(user).map { |repo| {label: repo.name, value: repo.size} }
  end

  def self.followers(user)
    service.followers(user)
  end

  def self.following(user)
    service.following(user)
  end

  def self.data(user)
    service.data(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController
  def index
    @followers = User.followers(current_user.nickname)
    @following = User.following(current_user.nickname)
  end

  def search
    if params[:id] == ""
      flash[:error] = "Please submit search parameters"
      redirect_to :back
    else
      @results = User.search(params[:id])
    end
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @followers = current_user.followers
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
  end

  def show
  end

  def specific_repo_data
    render :json => Repo.specific_repo_data(params[:user_id], params[:id])
  end

  def commit_data
    render :json => Repo.commit_data(params[:user_id], params[:id])
  end

  def commit_activity
    render :json => Repo.commit_activity(params[:user_id], params[:id])
  end

  def language_data
    render :json => Repo.language_data(params[:user_id], params[:id])
  end

  def contributor_data
    render :json => Repo.contributor_data(params[:user_id], params[:id])
  end

  def code_frequency
    render :json => Repo.code_frequency(params[:user_id], params[:id])
  end

  def pull_requests
    render :json => Repo.pull_requests(params[:user_id], params[:id])
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def welcome
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    flash[:notice] = "Welcome, #{user.nickname}"
    redirect_to user_path(user.nickname)
  end

  def destroy
    session.clear
    flash[:notice] = "Goodbye!"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def repo_data
    render :json => User.repo_data(params[:id])
  end

  def follower_data
    render :json => User.followers(params[:id])
  end

  def user_data
    render :json => User.data(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/explore/index.html.erb
<div class="container top-margin">
  <div class="row">
    <div class="col s2">
      <h5>Followers</h5>
      <div class="followers">
        <% @followers.each do |follower| %>
        <p>
          <%= image_tag("#{follower.avatar_url}") %>
          <%= link_to follower.login, user_path(follower.login) %>
        </p>
        <% end %>
      </div>
    </div>
    <div class="col s6 offset-s1 center">
      <h5>Search for a user Below!</h5>
      <%= form_tag("/search", method: "get", id: "searchForm") do %>
      <%= label_tag(:id, "Search for:") %>
      <%= text_field_tag(:id) %>
      <%= submit_tag("Search", class: 'btn btn-small') %>
      <% end %>
    </div>
    <div class="col s2 offset-s1 right-align">
      <h5>Following</h5>
      <div class="following">
        <% @following.each do |following| %>
        <p>
          <%= link_to following.login, user_path(following.login) %>
          <%= image_tag("#{following.avatar_url}") %>
        </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/explore/search.html.erb
<div class="container">
  <div class="row center">
    <div class="col s4 offset-s4">
      <h5><%= @results.total_count %> Results!</h5>
      <% if @results.total_count > 100 %>
        <h6>(only showing the first 100)</h6>
      <% end %>
    </div>
    <div class="col s8 offset-s2 search-results">
      <% @results.items.each do |result| %>
      <p>
        <%= image_tag("#{result.avatar_url}") %>
        <%= link_to result.login, user_path(result.login) %>
      </p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitBetterGraphs</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: 'partials/nav' %>
  <% flash.each do |type, msg| %>
  <div class="flash_<%= type %>">
    <%= content_tag :p, msg, class: 'hidden' %>
    <script type="text/javascript">
      Materialize.toast('<%= sanitize(msg) %>', 5000, 'rounded <%= "flash_#{type}" %>');
    </script>
  </div>
  <% end %>  <%= yield %>
</body>
</html>

app/views/partials/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5><%= link_to "GitBetter Graphs", "https://github.com/rossedfort/git_better_graphs", target: "_blank" %></h5>
        <p>A Ruby on Rails app built using AJAX and D3js</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5>Links</h5>
        <ul>
          <li><%= link_to "Gihtub API", "https://developer.github.com/v3/", target: "_blank"%></li>
          <li><%= link_to "Twitter", "https://twitter.com/rossedfort", target: "_blank"%></li>
          <li><%= link_to "LinkedIn", "https://www.linkedin.com/in/rossedfort", target: "_blank"%></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/partials/_nav.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="<%= root_path %>" class="brand-logo center">GitBetter Graphs</a>
    <ul id="nav-mobile" class="left hide-on-med-and-down">
        <% if current_user %>
          <li><%= link_to "Logout", logout_path %></li>
        <% else %>
        <li><%= link_to "Login", login_path %></li>
        <% end %>
    </ul>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if current_user %>
      <li><%= link_to "Explore", explore_path %></li>
      <li><%= link_to "myGraphs", user_path(current_user.nickname) %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/repos/show.html.erb
<%= javascript_tag "var userName = '#{User.data(params[:user_id]).login}';" %>
<%= javascript_tag "var repoName = '#{Repo.specific_repo_data(params[:user_id], params[:id]).name}';" %>

<div class="repo-data">
  <div class="container">
    <div class="row">
      <div class="col s8">
        <h5>name:</h5>
        <p id="repoName"></p><br>
        <h5>description:</h5>
        <p id="repoDescription"></p><br>
        <h5>primary language:</h5>
        <p id="repoLanguage"></p><br>
        <div class="col s4 repo-dropdown">
          <form>
            <select class="browser-default" name="repoSelect" id="repoSelect">
              <option disabled>choose a different repo...</option>
            </select>
          </form>
        </div>
      </div>
      <div class="col s4">
        <table class="bordered highlight">
          <tr>
            <th>watchers:</th>
            <td id="repoWatchers"></td>
            <th>open issues:</th>
            <td id="repoOpenIssues"></td>
          </tr>
          <tr>
            <th>commits:</th>
            <td id="commitCount"></td>
            <th>contributors:</th>
            <td id="repoContributors"></td>
          </tr>
          <tr>
            <th>forks:</th>
            <td id="repoForks"></td>
            <th>size in lines:</th>
            <td id="repoSize"></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="repo-buttons">
  <div class="container">
    <div class="row">
      <div class="col s12 center graph-selection">
        <button id="contributorGraphButton" type="button" class="btn blue btn-small">contributor</button>
        <button id="languageGraphButton" type="button" class="btn blue btn-small">language</button>
        <button id="commitGraphButton" type="button" class="btn blue btn-small">commit</button>
        <button id="frequencyGraphButton" type="button" class="btn blue btn-small">frequency</button>
        <button id="pullRequestGraphButton" type="button" class="btn blue btn-small">pulls</button>
      </div>
    </div>
  </div>
</div>
<div class="repo-graphs">
  <div class="container">
    <div class="graphs center">
      <h5>Click a button above and your graph will appear here!</h5><br>
      <h5>If there is no data for that repository, a graph will not appear</h5>
      <div class="hidden" id="languageDataGraph">
        <h6>Shows the breakdown of what languages are used in the repo</h6><br>
        <div class="languageLoader large-top-margin center loader">
          <%= image_tag("loader.svg") %>
          <h5 class="center">thinking...</h5>
        </div>
      </div>
      <div class="hidden" id="contributorDataGraph">
        <h6>Shows the breakdown of who has contributed to the repo</h6><br>
        <div class="contributorLoader large-top-margin center loader">
          <%= image_tag("loader.svg") %>
          <h5 class="center">thinking...</h5>
        </div>
      </div>
      <div class="hidden" id="commitGraph">
        <h6>Compares the amount of</h6><h6 class="text-blue"> commits </h6><h6>against time in the past year</h6><br>
        <div class="commitLoader large-top-margin center loader">
          <%= image_tag("loader.svg") %>
          <h5 class="center">thinking...</h5>
        </div>
      </div>
      <div class="hidden" id="frequencyGraph">
        <h6>Shows the amount of code deleted in</h6><h6 class="text-red"> red </h6><h6>and added in</h6><h6 class="text-green"> green </h6><h6>per week</h6><br>
        <div class="frequencyLoader large-top-margin center loader">
          <%= image_tag("loader.svg") %>
          <h5 class="center">thinking...</h5>
        </div>
      </div>
      <div class="hidden" id="pullRequestGraph">
        <h6>Shows the amount of open vs. closed pull requests</h6><br>
        <div class="pullRequestLoader large-top-margin center loader">
          <%= image_tag("loader.svg") %>
          <h5 class="center">thinking...</h5>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/root/welcome.html.erb
<div class="container center">
  <h3>Better Graphs for Github!</h3>
  <h5 class="grey-text text-lighten-1">
    GitBetter Graphs consumes the Github API to display, and graphically represent
    data for Github users, commits, repositories, and more. This service is perfect for
    developers who want a better view into the data associated with their Github
    accounts. It's also tailored to recruiters and employers for gathering data
    on potential employees. Click <%= link_to "login", login_path %> to get started!
  </h5>
  <div class="slider small-top-margin">
    <ul class="slides">
      <li>
        <%= image_tag('graph_one.png') %>
      </li>
      <li>
        <%= image_tag('graph_two.png') %>
      </li>
      <li>
        <%= image_tag('graph_three.png') %>
      </li>
      <li>
        <%= image_tag('graph_four.png') %>
      </li>
    </ul>
  </div>
</div>
<%= render partial: 'partials/footer' %>

app/views/users/index.html.erb
<canvas class="canvas"></canvas>

app/views/users/show.html.erb
<%= javascript_tag "var userName = '#{User.data(params[:id]).login}';" %>
<div class="container">
  <div class="row stats-row">
    <div class="col s5 offset-s1">
      <table class="centered">
        <thead>
          <tr>
            <th>Username</th>
            <th>Followers</th>
            <th>Following</th>
            <th>Repos</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td id="userData"></td>
            <td id="userFollowerCount"></td>
            <td id="userFollowingCount"></td>
            <td id="userRepoCount"></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col s3 offset-s2 repo-dropdown">
      <h5>select a repository to begin!</h5>
      <form>
        <select class="browser-default" name="repoSelect" id="repoSelect">
          <option disabled>choose a repo...</option>
        </select>
      </form>
    </div>
  </div>
  <div class="center">
    <div class="repoLoader">
      <%= image_tag("loader.svg") %>
    </div>
    <svg id="user_repo_graph"></svg>
  </div>
</div>